version: '3.7'
services:
  control:
    volumes:
      - ${GOPATH}/bin:/gobin # Mounts $GOPATH/bin on host to /gobin for easy access to binaries.
  jaeger:
    networks:
      - jepsen
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  grafana:
    networks:
      - jepsen
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
    - 3000:3000
    volumes:
    - type: volume
      source: grafana-volume
      target: /var/lib/grafana
      read_only: false
  node-exporter:
    networks:
      - jepsen
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    pid: host
    working_dir: /working/jaeger
    volumes:
    - type: bind
      source: /
      target: /host
      read_only: true
  prometheus:
    networks:
      - jepsen
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
    - 9090:9090
    volumes:
    - type: volume
      source: prometheus-volume
      target: /prometheus
      read_only: false
    - type: bind
      source: $JEPSEN_ROOT/dgraph/docker/prometheus.yml
      target: /etc/prometheus/prometheus.yml
      read_only: true

volumes:
  grafana-volume: {}
  prometheus-volume: {}
